import QuantumQueryComplexity.Dual
set_option linter.style.header false
set_option linter.unusedSectionVars false

/-!
# The adversary bound on a promise domain

`advPM f` is a single worst-case number attached to a *total* function on the
cube `ι → σ`.  Some bounds are genuinely instance-sensitive: the semilattice
product costs `O(√(n log|L_x|))` where `L_x` is generated by the letters of the
input `x` at hand, and that cannot be said with a free `x` on only one side of
an inequality about a total function.

The fix is to let the inputs be an arbitrary finite type `X` together with an
**observation map**

  `read : X → ι → σ`,

so that a query at `i` returns `read x i`.  Every occurrence of `x i = y i` in
the definitions becomes `read x i = read y i`, and nothing else changes:
`advPMOn`, `DualPairOn` and weak duality are the same statements with the cube
replaced by `X`.  The total case is `X = (ι → σ)` with `read x = x`.

The point of the definitions is `DualPair.restrictTo`: a dual solution for a
total function restricts to the promise **at no cost**, and the restricted cost
is the maximum of the *pointwise* masses over the promise only.  So a bound whose
per-input analysis needs a hypothesis about that input — a critical budget, say —
gives a promise bound as soon as the promise guarantees the hypothesis.
-/

namespace QuantumQueryComplexity

open scoped Matrix Matrix.Norms.L2Operator
open Matrix

variable {ι : Type*} [Fintype ι] [DecidableEq ι]
variable {σ : Type*} [DecidableEq σ]
variable {X : Type*} [Fintype X] [DecidableEq X]
variable {O : Type*}

/-! ## The primal bound -/

/-- The difference matrix of a promise domain: `1` exactly when a query at `i`
distinguishes the two promise inputs. -/
def advDOn (read : X → ι → σ) (i : ι) : Matrix X X ℝ :=
  Matrix.of fun x y => if read x i = read y i then 0 else 1

@[simp] lemma advDOn_apply (read : X → ι → σ) (i : ι) (x y : X) :
    advDOn read i x y = if read x i = read y i then 0 else 1 := rfl

lemma advDOn_isHermitian (read : X → ι → σ) (i : ι) :
    (advDOn read i).IsHermitian := by
  show (advDOn read i)ᴴ = advDOn read i
  ext x y
  simp [Matrix.conjTranspose_apply, advDOn, eq_comm]

lemma hadamard_advDOn_apply (read : X → ι → σ) (Γ : Matrix X X ℝ) (i : ι)
    (x y : X) :
    (Γ ⊙ advDOn read i) x y = if read x i = read y i then 0 else Γ x y := by
  rw [Matrix.hadamard_apply, advDOn_apply]
  by_cases h : read x i = read y i <;> simp [h]

/-- An adversary matrix on a promise domain. -/
def IsAdvMatrixOn (f : X → O) (Γ : Matrix X X ℝ) : Prop :=
  Γ.IsHermitian ∧ ∀ x y, f x = f y → Γ x y = 0

lemma isAdvMatrixOn_zero (f : X → O) : IsAdvMatrixOn f (0 : Matrix X X ℝ) :=
  ⟨Matrix.isHermitian_zero, fun _ _ _ => rfl⟩

/-- **The adversary bound of a function on a promise domain.** -/
noncomputable def advPMOn (read : X → ι → σ) (f : X → O) : ℝ :=
  sSup {r : ℝ | ∃ Γ, IsAdvMatrixOn f Γ ∧ (∀ i, ‖Γ ⊙ advDOn read i‖ ≤ 1) ∧ r = ‖Γ‖}

lemma advPMOn_set_nonempty (read : X → ι → σ) (f : X → O) :
    {r : ℝ | ∃ Γ, IsAdvMatrixOn f Γ ∧ (∀ i, ‖Γ ⊙ advDOn read i‖ ≤ 1)
      ∧ r = ‖Γ‖}.Nonempty := by
  refine ⟨0, 0, isAdvMatrixOn_zero f, fun i => ?_, ?_⟩
  · rw [Matrix.zero_hadamard]
    simp
  · simp

theorem advPMOn_le {read : X → ι → σ} {f : X → O} {c : ℝ}
    (hc : ∀ Γ, IsAdvMatrixOn f Γ → (∀ i, ‖Γ ⊙ advDOn read i‖ ≤ 1) → ‖Γ‖ ≤ c) :
    advPMOn read f ≤ c := by
  refine csSup_le (advPMOn_set_nonempty read f) ?_
  rintro r ⟨Γ, h1, h2, rfl⟩
  exact hc Γ h1 h2

/-! ## The dual -/

variable [DecidableEq O]

/-- A feasible dual solution on a promise domain. -/
structure DualPairOn {ι : Type*} [Fintype ι] {σ : Type*} [DecidableEq σ]
    {X : Type*} [Fintype X] {O : Type*} [DecidableEq O]
    (read : X → ι → σ) (K : Type*) [Fintype K] (f : X → O) where
  /-- The first vector family. -/
  u : X → ι → K → ℝ
  /-- The second vector family. -/
  v : X → ι → K → ℝ
  /-- Feasibility, with the mask read through `read`. -/
  constraint : ∀ x y : X,
    (∑ i, if read x i = read y i then 0 else ∑ k, u x i k * v y i k)
      = if f x = f y then 0 else 1

namespace DualPairOn

variable {K : Type*} [Fintype K] {read : X → ι → σ} {f : X → O}

/-- The cost of a dual solution on a promise domain. -/
def IsCostLe (P : DualPairOn read K f) (c : ℝ) : Prop :=
  (∀ x, ∑ i, ∑ k, P.u x i k * P.u x i k ≤ c) ∧
  (∀ x, ∑ i, ∑ k, P.v x i k * P.v x i k ≤ c)

lemma IsCostLe.mono {P : DualPairOn read K f} {c d : ℝ} (h : P.IsCostLe c)
    (hcd : c ≤ d) : P.IsCostLe d :=
  ⟨fun x => (h.1 x).trans hcd, fun x => (h.2 x).trans hcd⟩

end DualPairOn

set_option maxHeartbeats 800000 in
/-- **Weak duality on a promise domain.**  The same Gram-plus-Cauchy–Schwarz
argument as `advPM_le_of_dualPair`; only the mask is read through `read`. -/
theorem advPMOn_le_of_dualPairOn {K : Type*} [Fintype K] {read : X → ι → σ}
    {f : X → O} (P : DualPairOn read K f) {c : ℝ} (hc : 0 ≤ c)
    (hP : P.IsCostLe c) : advPMOn read f ≤ c := by
  refine advPMOn_le fun Γ hΓ hΓD => ?_
  refine l2_opNorm_le_of_forall_dotProduct Γ hc fun a b => ?_
  have hsplit : ∀ x y, a x * Γ x y * b y
      = ∑ p : ι × K, (a x * P.u x p.1 p.2) * (Γ ⊙ advDOn read p.1) x y *
          (b y * P.v y p.1 p.2) := by
    intro x y
    rw [Fintype.sum_prod_type]
    show a x * Γ x y * b y
      = ∑ i, ∑ k, (a x * P.u x i k) * (Γ ⊙ advDOn read i) x y * (b y * P.v y i k)
    have hstep : ∀ i : ι,
        (∑ k, (a x * P.u x i k) * (Γ ⊙ advDOn read i) x y * (b y * P.v y i k))
        = (a x * b y * Γ x y) *
            (if read x i = read y i then 0 else ∑ k, P.u x i k * P.v y i k) := by
      intro i
      by_cases hi : read x i = read y i
      · rw [if_pos hi, mul_zero]
        refine Finset.sum_eq_zero fun k _ => ?_
        rw [hadamard_advDOn_apply, if_pos hi]
        ring
      · rw [if_neg hi, Finset.mul_sum]
        refine Finset.sum_congr rfl fun k _ => ?_
        rw [hadamard_advDOn_apply, if_neg hi]
        ring
    rw [Finset.sum_congr rfl fun i (_ : i ∈ Finset.univ) => hstep i,
      ← Finset.mul_sum, P.constraint x y]
    by_cases hg : f x = f y
    · rw [if_pos hg, hΓ.2 x y hg]
      ring
    · rw [if_neg hg]
      ring
  have hexpand : a ⬝ᵥ Γ *ᵥ b
      = ∑ p : ι × K, (fun x => a x * P.u x p.1 p.2) ⬝ᵥ
          (fun i => Γ ⊙ advDOn read i) p.1 *ᵥ (fun y => b y * P.v y p.1 p.2) := by
    rw [dotProduct_mulVec_eq_sum]
    have hrhs : (∑ p : ι × K, (fun x => a x * P.u x p.1 p.2) ⬝ᵥ
        (fun i => Γ ⊙ advDOn read i) p.1 *ᵥ (fun y => b y * P.v y p.1 p.2))
        = ∑ p : ι × K, ∑ x, ∑ y, (a x * P.u x p.1 p.2) *
            (Γ ⊙ advDOn read p.1) x y * (b y * P.v y p.1 p.2) :=
      Finset.sum_congr rfl fun p _ => dotProduct_mulVec_eq_sum _ _ _
    rw [hrhs]
    conv_rhs => rw [Finset.sum_comm]
    refine Finset.sum_congr rfl fun x _ => ?_
    conv_rhs => rw [Finset.sum_comm]
    exact Finset.sum_congr rfl fun y _ => hsplit x y
  rw [hexpand]
  exact key_bound (fun i => Γ ⊙ advDOn read i) hΓD a b P.u P.v hc hP.1 hP.2

/-! ## Restricting a total dual solution to a promise -/

namespace DualPair

variable {K : Type*} [Fintype K] [Fintype σ] {g : (ι → σ) → O}

/-- **A total dual solution restricted to a promise domain.**  The vectors are
unchanged: the promise constraint at `(x, y)` is the total constraint at
`(read x, read y)`. -/
def restrictTo (P : DualPair K g) (read : X → ι → σ) :
    DualPairOn read K (fun x => g (read x)) where
  u x := P.u (read x)
  v y := P.v (read y)
  constraint x y := P.constraint (read x) (read y)

/-- The restricted cost is the maximum of the *pointwise* masses **over the
promise only** — which is the entire point of the construction. -/
theorem restrictTo_isCostLe {P : DualPair K g} {read : X → ι → σ} {c : ℝ}
    (hu : ∀ x : X, (∑ i, ∑ k, P.u (read x) i k * P.u (read x) i k) ≤ c)
    (hv : ∀ x : X, (∑ i, ∑ k, P.v (read x) i k * P.v (read x) i k) ≤ c) :
    (P.restrictTo read).IsCostLe c := ⟨hu, hv⟩

end DualPair

end QuantumQueryComplexity
